[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "backend"
source = "backend"

[services.build]
buildCommand = "npm install"
startCommand = "npm run migrate && npm start"

[services.variables]
NODE_ENV = "production"
JWT_SECRET = "adonai_farm_super_secure_secret_2024"

[[services]]
name = "frontend"
source = "frontend"

[services.build]
buildCommand = "npm install && npm run build"
startCommand = "npx serve -s dist -l $PORT"

[services.variables]
VITE_API_URL = "https://backend-production.railway.app"